export const moc = [
  // {
  //   topic: "Консультация по судимости",
  //   topic_icon: "https://storage.yandexcloud.net/akhidov-ivr/9.1.mp4",
  //   sections1_type: "На территории РФ",
  //   sections1: [
  //     "Круг заявителей",
  //     "Перечень документов",
  //     "Срок предоставления",
  //     "Госпошлина",
  //   ],
  //   sections1_icons: null,
  //   sections1_additional: null,
  //   sections1_additional_icons: null,
  //   sections2_type: "За пределами РФ",
  //   sections2: null,
  //   sections2_icons: null,
  //   sections2_additional: null,
  //   sections2_additional_icons: null,
  // },
  // {
  //   topic: "Консультация по СНИЛС",
  //   topic_icon: "https://storage.yandexcloud.net/akhidov-ivr/9.1.mp4",
  //   sections1_type: null,
  //   sections1: [
  //     "Круг заявителей",
  //     "Перечень документов",
  //     "Срок предоставления",
  //     "Госпошлина",
  //   ],
  //   sections1_icons: null,
  //   sections1_additional: null,
  //   sections1_additional_icons: null,
  //   sections2_type: null,
  //   sections2: null,
  //   sections2_icons: null,
  //   sections2_additional: null,
  //   sections2_additional_icons: null,
  // },
  // {
  //   topic: "Консультация по регистрационному учету",
  //   topic_icon: "https://storage.yandexcloud.net/akhidov-ivr/9.1.mp4",
  //   sections1_type: null,
  //   sections1: [
  //     "Постоянная регистрация ребенка до 14 лет",
  //     "Временная регистрация ребенка до 14 лет",
  //     "Постоянная регистрация несовершеннолетнего ребенка старше 14 лет",
  //     "Временная регистрация несовершеннолетнего ребенка старше 14 лет",
  //     "Постоянная регистрация гражданина старше 18 лет",
  //     "Временная регистрация гражданина старше 18 лет",
  //   ],
  //   sections1_icons: [
  //     "https://storage.yandexcloud.net/akhidov-ivr/9.1.mp4",
  //     "https://storage.yandexcloud.net/akhidov-ivr/9.1.mp4",
  //     "https://storage.yandexcloud.net/akhidov-ivr/9.1.mp4",
  //     "https://storage.yandexcloud.net/akhidov-ivr/9.1.mp4",
  //     "https://storage.yandexcloud.net/akhidov-ivr/9.1.mp4",
  //     "https://storage.yandexcloud.net/akhidov-ivr/9.1.mp4",
  //   ],
  //   sections1_additional: [],
  //   sections1_additional_icons: [],
  //   sections2_type: null,
  //   sections2: null,
  //   sections2_icons: null,
  //   sections2_additional: null,
  //   sections2_additional_icons: null,
  // },
  // {
  //   topic: "Консультация по паспорту Российской Федерации",
  //   topic_icon: "https://storage.yandexcloud.net/akhidov-ivr/9.1.mp4",
  //   sections1_type: null,
  //   sections1: [
  //     "Паспорт в 14 лет",
  //     "Паспорт в 20 лет или в 45 лет",
  //     "Изменение паспортных данных",
  //     "Непригодность паспорта",
  //     "Паспорт украден или утерян",
  //   ],
  //   sections1_icons: [
  //     "https://storage.yandexcloud.net/akhidov-ivr/9.1.mp4",
  //     "https://storage.yandexcloud.net/akhidov-ivr/9.1.mp4",
  //     "https://storage.yandexcloud.net/akhidov-ivr/9.1.mp4",
  //     "https://storage.yandexcloud.net/akhidov-ivr/9.1.mp4",
  //     "https://storage.yandexcloud.net/akhidov-ivr/9.1.mp4",
  //   ],
  //   sections1_additional: [
  //     "Госпошлина",
  //     "Документы удостоверяющие наличие гражданства Российской Федерации",
  //     "Срок предоставления услуги",
  //     "Фотографии",
  //     "Отметки в паспорте",
  //   ],
  //   sections1_additional_icons: [
  //     "https://storage.yandexcloud.net/akhidov-ivr/9.1.mp4",
  //     "https://storage.yandexcloud.net/akhidov-ivr/9.1.mp4",
  //     "https://storage.yandexcloud.net/akhidov-ivr/9.1.mp4",
  //     "https://storage.yandexcloud.net/akhidov-ivr/9.1.mp4",
  //     "https://storage.yandexcloud.net/akhidov-ivr/9.1.mp4",
  //   ],
  //   sections2_type: null,
  //   sections2: null,
  //   sections2_icons: null,
  //   sections2_additional: null,
  //   sections2_additional_icons: null,
  // },
  // {
  //   topic: "Консультация по ИНН",
  //   topic_icon: "https://storage.yandexcloud.net/akhidov-ivr/9.1.mp4",
  //   sections1_type: null,
  //   sections1: [
  //     "Круг заявителей",
  //     "Перечень документов",
  //     "Срок предоставления услуги",
  //     "Госпошлина",
  //   ],
  //   sections1_icons: null,
  //   sections1_additional: null,
  //   sections1_additional_icons: null,
  //   sections2_type: null,
  //   sections2: null,
  //   sections2_icons: null,
  //   sections2_additional: null,
  //   sections2_additional_icons: null,
  // },
  // {
  //   topic: "Консультация по водительскому удостоверению",
  //   topic_icon: "https://storage.yandexcloud.net/akhidov-ivr/9.1.mp4",
  //   sections1_type: "В России",
  //   sections1: [
  //     "Замена по смене персональных данных",
  //     "Замена по окончании срока действия, при изменении состояния здоровья, замена при утере, хищении (или удостоверение пришло в негодность), Замена удостоверения при волеизъявлении заявителя до истечении срока действия водительского удостоверения",
  //   ],
  //   sections1_icons: null,
  //   sections1_additional: [
  //     "Госпошлина",
  //     "Срок предоставления услуги",
  //     "Срок действия",
  //   ],
  //   sections1_additional_icons: null,
  //   sections2_type: "Заграницей",
  //   sections2: null,
  //   sections2_icons: null,
  //   sections2_additional: ["Общее", "Госпошлина", "Срок предоставления услуги"],
  //   sections2_additional_icons: null,
  // },
  // {
  //   topic: "Консультация по загранпаспорту",
  //   topic_icon: "https://storage.yandexcloud.net/akhidov-ivr/9.1.mp4",
  //   sections1_type: null,
  //   sections1: [
  //     "Старого образца. Ребенок до 14 лет",
  //     "Нового образца. Ребенок до 14 лет",
  //     "Старого образца. Ребенок после 14 лет",
  //     "Нового образца. Ребенок после 14 лет",
  //     "Старого образца. Совершеннолетний",
  //     "Нового образца. Совершеннолетний",
  //   ],
  //   sections1_icons: [
  //     "https://storage.yandexcloud.net/akhidov-ivr/9.1.mp4",
  //     "https://storage.yandexcloud.net/akhidov-ivr/9.1.mp4",
  //     "https://storage.yandexcloud.net/akhidov-ivr/9.1.mp4",
  //     "https://storage.yandexcloud.net/akhidov-ivr/9.1.mp4",
  //     "https://storage.yandexcloud.net/akhidov-ivr/9.1.mp4",
  //     "https://storage.yandexcloud.net/akhidov-ivr/9.1.mp4",
  //   ],
  //   sections1_additional: [
  //     "Как вернуть госпошлину?",
  //     "Госпошлина",
  //     "Требование к фото",
  //   ],
  //   sections1_additional_icons: null,
  //   sections2_type: null,
  //   sections2: [
  //     "Внесение изменений в паспорт старого образца/Вписать детей в загранпаспорт",
  //   ],
  //   sections2_icons: null,
  //   sections2_additional: null,
  //   sections2_additional_icons: null,
  // },
];
